<?php $stores = $this->getStores();?>
<?php if($stores->getSize()):?>
<div class="storelist-stores">
<?php foreach ($stores as $store): ?>
<div class="store">
    <h3><?php echo $store->getName();?></h3>
    <div class="gallery gallery-<?php echo $store->getId();?>"></div>
    <div class="store-info">
        <p><?php echo $store->getDescription();?></p>
        <p><?php echo __("Store Hours:");?></p>
        <p><?php echo $store->getHours();?></p>
        <p><a href="tel:<?php echo $store->getTelephone();?>"><?php echo $store->getTelephone();?></a></p>
    </div>
    <script type="text/x-magento-init">
         {
            ".gallery-<?php echo $store->getId();?>": {
                "mage/gallery/gallery": {
                     "data": <?php echo $store->getImages(); ?>,
                     "options": {
                        "nav" : "thumbs",
                        "transition" : "slide",
                        "navtype" : "thumbs",
                        "navdir" : "vertical",
                        "height" : 400,
                        "width" : 300,
                        "maxheight" : 400,
                        "maxwidth" : 300
                     },
                    "fullscreen" : {
                        "nav" : "thumbs"
                    }
                 }
            }
         }
    </script>
</div>
<?php endforeach;?>
</div>
<?php endif;?>

